### PR TITLE
Catch TimeoutError

### LINKED ISSUE #26: Timeout errors
I think this would be a good idea to handle in the main template, and shouldn't it to just try to reconnect rather than die completely?

```
Traceback (most recent call last):
  File "main.py", line 98, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "main.py", line 86, in main
    await client.sync_forever(timeout=30000, full_state=True)
  File "/home/sm/Github/dankbot/venv/lib/python3.7/site-packages/nio/client/async_client.py", line 1147, in sync_forever
    await self.run_response_callbacks([await response])
  File "/usr/lib/python3.7/asyncio/tasks.py", line 533, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/home/sm/Github/dankbot/venv/lib/python3.7/site-packages/nio/client/async_client.py", line 1003, in sync
    timeout,
  File "/home/sm/Github/dankbot/venv/lib/python3.7/site-packages/nio/client/async_client.py", line 705, in _send
    method, path, data, headers, trace_context, timeout,
  File "/home/sm/Github/dankbot/venv/lib/python3.7/site-packages/nio/client/async_client.py", line 252, in wrapper
    return await func(self, *args, **kwargs)
  File "/home/sm/Github/dankbot/venv/lib/python3.7/site-packages/nio/client/async_client.py", line 781, in send
    else timeout,
  File "/home/sm/Github/dankbot/venv/lib/python3.7/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/home/sm/Github/dankbot/venv/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/home/sm/Github/dankbot/venv/lib/python3.7/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
```

### PR DESCRIPTION
**Pull request by KevinLi**
Fixes #26

### CODE REVIEW

**Review by anoadragon453 — CHANGES_REQUESTED** [review]
Thank you for this! This is certainly a better approach than just crashing the bot :)

**Review by anoadragon453 — APPROVED** [review]
LGTM, thanks! I just added a comment which will hopefully help demystify why this could happen, and why it's not a concern.

**Comment by KevinLi** [comment]
Good thing you left this open; I left an instance running with 0 timeout as suggested, and woke up to 800 unreadable messages in its logging channel. Maybe we should close this without merging, or put that timeout back in.

**Comment by anoadragon453** [comment]
This project is no longer maintained. Thank you though!

**Pull request closed without merging**
